<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  PDFCanvasViewer,
  PDFDocument,
  PDFPage,
  PDFView,
  PDFText,
} from '@pdf.js/vue'
import type { PageSize } from '@pdf.js/vue'

const docTitle = ref('Hello PDFCraft')
const docSubtitle = ref('Canvas-rendered PDF preview')
const docAuthor = ref('PDFCraft')
const docBody = ref(
  'This PDF was generated entirely in the browser using PDFCraft. ' +
    'Edit the inputs on the right and watch the canvas update in real time.\n\n' +
    'PDFCraft uses pdf-lib under the hood with a Yoga-based flexbox layout engine, ' +
    'giving you full control over positioning, typography, and styling.',
)
const headerFontSize = ref(28)
const bodyFontSize = ref(12)
const headerColor = ref('#1e293b')
const accentColor = ref('#6366f1')
const bgColor = ref('#ffffff')
const pageSize = ref<PageSize>('A4')

const deps = computed(() => [
  docTitle.value, docSubtitle.value, docAuthor.value, docBody.value,
  headerFontSize.value, bodyFontSize.value,
  headerColor.value, accentColor.value, bgColor.value, pageSize.value,
])

const pageStyle = computed(() => ({ padding: 40, backgroundColor: bgColor.value }))
const barStyle = computed(() => ({
  height: 4, backgroundColor: accentColor.value, marginBottom: 20, borderRadius: 2,
}))
const headerStyle = computed(() => ({
  fontSize: headerFontSize.value, fontWeight: 'bold' as const,
  color: headerColor.value, textAlign: 'center' as const, marginBottom: 8,
}))
const subStyle = {
  fontSize: 13, fontStyle: 'italic' as const, color: '#94a3b8',
  textAlign: 'center' as const, marginBottom: 30,
}
const bodyStyle = computed(() => ({
  fontSize: bodyFontSize.value, color: '#374151', lineHeight: 1.7,
}))
const footerStyle = { fontSize: 9, color: '#9ca3af', textAlign: 'center' as const, paddingTop: 40 }
</script>

<template>
  <div class="cv">
    <PDFCanvasViewer :deps="deps" width="100%" height="100%">
      <PDFDocument :title="docTitle" :author="docAuthor">
        <PDFPage :size="pageSize" :style="pageStyle">
          <PDFView :style="barStyle" />
          <PDFText :style="headerStyle">{{ docTitle }}</PDFText>
          <PDFText :style="subStyle">{{ docSubtitle }}</PDFText>
          <PDFView :style="{ marginTop: 10 }">
            <PDFText :style="bodyStyle">{{ docBody }}</PDFText>
          </PDFView>
          <PDFText :style="footerStyle">
            Generated by {{ docAuthor }} — PDFCraft
          </PDFText>
        </PDFPage>
      </PDFDocument>
    </PDFCanvasViewer>

    <aside class="cv-sidebar">
      <div class="cv-sec">
        <h3 class="cv-sec-title">Document</h3>
        <label class="cv-field">
          <span>Title</span>
          <input v-model="docTitle" />
        </label>
        <label class="cv-field">
          <span>Subtitle</span>
          <input v-model="docSubtitle" />
        </label>
        <label class="cv-field">
          <span>Author</span>
          <input v-model="docAuthor" />
        </label>
        <label class="cv-field">
          <span>Body</span>
          <textarea v-model="docBody" rows="5" />
        </label>
        <label class="cv-field">
          <span>Page size</span>
          <select v-model="pageSize">
            <option value="A4">A4</option>
            <option value="LETTER">Letter</option>
            <option value="LEGAL">Legal</option>
          </select>
        </label>
      </div>

      <div class="cv-sec">
        <h3 class="cv-sec-title">Appearance</h3>
        <label class="cv-field cv-field--range">
          <span>Header size</span>
          <input v-model.number="headerFontSize" type="range" min="14" max="48" />
          <em>{{ headerFontSize }}px</em>
        </label>
        <label class="cv-field cv-field--range">
          <span>Body size</span>
          <input v-model.number="bodyFontSize" type="range" min="8" max="24" />
          <em>{{ bodyFontSize }}px</em>
        </label>
        <div class="cv-colors">
          <label class="cv-color">
            <span>Header</span>
            <input v-model="headerColor" type="color" />
          </label>
          <label class="cv-color">
            <span>Accent</span>
            <input v-model="accentColor" type="color" />
          </label>
          <label class="cv-color">
            <span>Background</span>
            <input v-model="bgColor" type="color" />
          </label>
        </div>
      </div>
    </aside>
  </div>
</template>

<style scoped>
.cv {
  display: flex;
  height: calc(100vh - 43px);
  overflow: hidden;
}

.cv-sidebar {
  width: 300px;
  background: #fff;
  border-left: 1px solid #e2e8f0;
  overflow-y: auto;
  flex-shrink: 0;
}

.cv-sec {
  padding: 16px;
  border-bottom: 1px solid #f1f5f9;
}

.cv-sec-title {
  font-size: 11px;
  font-weight: 700;
  color: #94a3b8;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin: 0 0 12px;
}

.cv-field {
  display: flex;
  flex-direction: column;
  gap: 4px;
  margin-bottom: 10px;
}
.cv-field > span {
  font-size: 12px;
  font-weight: 600;
  color: #475569;
}
.cv-field input:not([type='color']):not([type='range']),
.cv-field textarea,
.cv-field select {
  padding: 7px 10px;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  font-size: 13px;
  color: #1e293b;
  background: #f8fafc;
  transition: border-color 0.15s;
  font-family: inherit;
  resize: vertical;
}
.cv-field input:focus,
.cv-field textarea:focus,
.cv-field select:focus {
  outline: none;
  border-color: #6366f1;
  box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1);
}

.cv-field--range {
  flex-direction: row;
  align-items: center;
  flex-wrap: wrap;
}
.cv-field--range > span {
  flex: 0 0 80px;
}
.cv-field--range input[type='range'] {
  flex: 1;
  min-width: 60px;
}
.cv-field--range em {
  font-style: normal;
  font-size: 12px;
  color: #94a3b8;
  min-width: 42px;
  text-align: right;
  font-variant-numeric: tabular-nums;
}

.cv-colors {
  display: flex;
  gap: 12px;
  margin-bottom: 10px;
}
.cv-color {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  flex: 1;
}
.cv-color span {
  font-size: 11px;
  font-weight: 600;
  color: #475569;
}
.cv-color input[type='color'] {
  width: 100%;
  height: 32px;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  cursor: pointer;
  padding: 2px;
  background: #f8fafc;
}
</style>
