import {
  Document,
  Page,
  View,
  Text,
  Image,
  Link,
  StyleSheet,
  renderToBuffer,
  renderToFile,
} from '../dist/index.mjs'

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1a1a2e',
    marginBottom: 10,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#666666',
    textAlign: 'center',
    marginBottom: 30,
  },
  section: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: '#f0f4f8',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#d1d5db',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2d3748',
    marginBottom: 8,
  },
  text: {
    fontSize: 11,
    color: '#4a5568',
    lineHeight: 1.6,
  },
  footer: {
    fontSize: 9,
    color: '#999999',
    textAlign: 'center',
    marginTop: 40,
  },
})

const doc = Document({ title: 'PDFCraft Demo', author: 'PDFCraft' }, [
  Page({ size: 'A4', style: styles.page }, [
    Text({ style: styles.header }, 'PDFCraft Demo Document'),
    Text({ style: styles.subtitle }, 'Generated with @pdfcraft/core'),

    View({ style: styles.section }, [
      Text({ style: styles.sectionTitle }, 'What is PDFCraft?'),
      Text(
        { style: styles.text },
        'PDFCraft is a framework-agnostic PDF generation library that uses PDFKit under the hood. ' +
          'It provides a component-based API similar to react-pdf, but works with Vue, Svelte, ' +
          'or plain JavaScript.',
      ),
    ]),

    View({ style: styles.section }, [
      Text({ style: styles.sectionTitle }, 'Features'),
      Text(
        { style: styles.text },
        '• Component-based API: Document, Page, View, Text, Image, Link\n' +
          '• StyleSheet API for reusable styles\n' +
          '• Works in Node.js and browsers\n' +
          '• SSR and CSR support\n' +
          '• Custom font registration\n' +
          '• PDF form support via PDFKit',
      ),
    ]),

    View({ style: styles.section }, [
      Text({ style: styles.sectionTitle }, 'Styled Text Examples'),
      Text(
        { style: { ...styles.text, textDecoration: 'underline' } },
        'This text is underlined.',
      ),
      Text(
        { style: { ...styles.text, fontWeight: 'bold', color: '#e53e3e' } },
        'This text is bold and red.',
      ),
      Text(
        { style: { ...styles.text, fontStyle: 'italic' } },
        'This text is italic.',
      ),
    ]),

    Text({ style: styles.footer }, 'Page 1 — Generated by PDFCraft'),
  ]),
])

console.log('Rendering PDF...')
const buffer = await renderToBuffer(doc)
console.log(`PDF generated: ${buffer.byteLength} bytes`)

await renderToFile(doc, 'test-output.pdf')
console.log('Saved to test-output.pdf')
